//
//  TMTImageConfiguration.swift
//  The Movies Tracker
//
//  Created by Leandro Lopes on 29/07/17.
//  Copyright © 2017 Tinfoil Hat Studios. All rights reserved.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


class TMTImageConfiguration: TMTJSONCompatible {
    var base_url: String
    var backdrop_sizes: [String]
    var secure_base_url: String
    var still_sizes: [String]
    var poster_sizes: [String]
    var logo_sizes: [String]
    var profile_sizes: [String]


    required init?(json: [String: Any]?) {
        guard let json = json else {return nil}
        base_url = json["base_url"] as? String ?? ""
        backdrop_sizes = json["backdrop_sizes"] as? [String] ?? []
        secure_base_url = json["secure_base_url"] as? String ?? ""
        still_sizes = json["still_sizes"] as? [String] ?? []
        poster_sizes = json["poster_sizes"] as? [String] ?? []
        logo_sizes = json["logo_sizes"] as? [String] ?? []
        profile_sizes = json["profile_sizes"] as? [String] ?? []
    }



    required convenience init() {
        self.init(json: [:])!
    }



    required convenience init?(data: Data?) {
        guard let data = data else {return nil}
        guard let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {return nil}
        self.init(json: json)
    }



    init(base_url: String, backdrop_sizes: [String], secure_base_url: String, still_sizes: [String], poster_sizes: [String], logo_sizes: [String], profile_sizes: [String]) {
        self.base_url = base_url
        self.backdrop_sizes = backdrop_sizes
        self.secure_base_url = secure_base_url
        self.still_sizes = still_sizes
        self.poster_sizes = poster_sizes
        self.logo_sizes = logo_sizes
        self.profile_sizes = profile_sizes
    }



    func jsonDictionary() -> [String: Any] {
        var dict: [String: Any] = [:]
        dict["base_url"] = base_url
        dict["backdrop_sizes"] = backdrop_sizes
        dict["secure_base_url"] = secure_base_url
        dict["still_sizes"] = still_sizes
        dict["poster_sizes"] = poster_sizes
        dict["logo_sizes"] = logo_sizes
        dict["profile_sizes"] = profile_sizes
        return dict
    }



}



