//
//  TMTProductionCountry.swift
//  The Movies Tracker
//
//  Created by Leandro Lopes on 28/07/17.
//  Copyright © 2017 Tinfoil Hat Studios. All rights reserved.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


class TMTProductionCountry: TMTJSONCompatible {
    var name: String
    var iso_3166_1: String


    required init?(json: [String: Any]?) {
        guard let json = json else {return nil}
        name = json["name"] as? String ?? ""
        iso_3166_1 = json["iso_3166_1"] as? String ?? ""
    }



    required convenience init() {
        self.init(json: [:])!
    }



    required convenience init?(data: Data?) {
        guard let data = data else {return nil}
        guard let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {return nil}
        self.init(json: json)
    }



    init(name: String, iso_3166_1: String) {
        self.name = name
        self.iso_3166_1 = iso_3166_1
    }



    func jsonDictionary() -> [String: Any] {
        var dict: [String: Any] = [:]
        dict["name"] = name
        dict["iso_3166_1"] = iso_3166_1
        return dict
    }



}



